using System.IO;
using System.Text;
using RukiCheck.Models;

namespace RukiCheck.Infrastructure;

/// <summary>
/// Markdown レポート生成サービス
/// </summary>
public class MarkdownReportGenerator
{
    /// <summary>
    /// Markdownレポートを生成
    /// </summary>
    public void Generate(InspectionReport report, string outputPath)
    {
        var markdown = BuildMarkdown(report);
        File.WriteAllText(outputPath, markdown, new UTF8Encoding(true)); // UTF-8 BOM
    }

    private string BuildMarkdown(InspectionReport report)
    {
        var sb = new StringBuilder();

        // タイトル
        sb.AppendLine("# 🔍 RukiCheck 検品レポート");
        sb.AppendLine();

        // メタ情報
        sb.AppendLine("## 📋 検品情報");
        sb.AppendLine();
        sb.AppendLine($"- **管理番号**: {report.Meta.ManagementId}");
        sb.AppendLine($"- **検品日**: {report.Meta.InspectionDate}");
        sb.AppendLine($"- **検品時刻**: {report.Meta.InspectionTime}");
        sb.AppendLine($"- **検品モード**: {report.Meta.Mode}");
        sb.AppendLine($"- **ツールバージョン**: {report.Meta.ToolVersion}");
        sb.AppendLine();

        // ハードウェア情報
        if (report.Hardware != null)
        {
            sb.AppendLine(BuildHardwareSection(report.Hardware));
        }

        // ストレージ
        if (report.Storage != null)
        {
            sb.AppendLine(BuildStorageSection(report.Storage));
        }

        // キーボード
        if (report.Keyboard != null)
        {
            sb.AppendLine(BuildKeyboardSection(report.Keyboard));
        }

        // マイク
        if (report.Microphone != null)
        {
            sb.AppendLine(BuildMicrophoneSection(report.Microphone));
        }

        // スピーカー
        if (report.Speaker != null)
        {
            sb.AppendLine(BuildSpeakerSection(report.Speaker));
        }

        // カメラ
        if (report.Camera != null)
        {
            sb.AppendLine(BuildCameraSection(report.Camera));
        }

        // トラックパッド
        if (report.Trackpad != null)
        {
            sb.AppendLine(BuildTrackpadSection(report.Trackpad));
        }

        // CPU
        if (report.Cpu != null)
        {
            sb.AppendLine(BuildCpuSection(report.Cpu));
        }

        // フッター
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("*Generated by RukiCheck Portable Inspection Tool*");
        sb.AppendLine();

        return sb.ToString();
    }

    private string BuildHardwareSection(HardwareInfoResult hardware)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## 🖥️ ハードウェア情報");
        sb.AppendLine();

        // システム情報
        sb.AppendLine("### 🏷️ システム情報");
        sb.AppendLine();
        sb.AppendLine($"- **メーカー**: {hardware.System.Manufacturer}");
        sb.AppendLine($"- **型番**: {hardware.System.Model}");
        sb.AppendLine($"- **シリアルナンバー**: {hardware.System.SerialNumber}");
        sb.AppendLine($"- **BIOSバージョン**: {hardware.System.BiosVersion}");
        sb.AppendLine();

        // CPU
        sb.AppendLine("### 💻 CPU");
        sb.AppendLine();
        sb.AppendLine($"- **モデル名**: {hardware.Cpu.Name}");
        sb.AppendLine($"- **製造元**: {hardware.Cpu.Manufacturer}");
        sb.AppendLine($"- **物理コア数**: {hardware.Cpu.Cores} コア");
        sb.AppendLine($"- **論理プロセッサ数**: {hardware.Cpu.LogicalProcessors} スレッド");
        sb.AppendLine($"- **最大クロック速度**: {hardware.Cpu.MaxClockMhz / 1000.0:F2} GHz");
        sb.AppendLine($"- **アーキテクチャ**: {hardware.Cpu.Architecture}");
        sb.AppendLine();

        // メモリ
        sb.AppendLine("### 🧠 メモリ");
        sb.AppendLine();
        sb.AppendLine($"- **総容量**: {hardware.Memory.TotalGb:F2} GB");
        sb.AppendLine($"- **メモリ種別**: {hardware.Memory.Type}");
        sb.AppendLine($"- **速度**: {hardware.Memory.SpeedMhz} MHz");
        sb.AppendLine($"- **スロット数**: {hardware.Memory.Slots}");
        sb.AppendLine();

        if (hardware.Memory.Modules.Count > 0)
        {
            sb.AppendLine("#### メモリモジュール詳細");
            sb.AppendLine();
            sb.AppendLine("| スロット | 容量 | メーカー | 速度 | パーツ番号 |");
            sb.AppendLine("|---------|------|---------|------|-----------|");
            for (int i = 0; i < hardware.Memory.Modules.Count; i++)
            {
                var module = hardware.Memory.Modules[i];
                sb.AppendLine($"| #{i + 1} | {module.CapacityGb:F2} GB | {module.Manufacturer} | {module.SpeedMhz} MHz | {module.PartNumber} |");
            }
            sb.AppendLine();
        }

        // GPU
        if (hardware.Gpus.Count > 0)
        {
            sb.AppendLine("### 🎮 GPU（グラフィックカード）");
            sb.AppendLine();
            foreach (var gpu in hardware.Gpus)
            {
                sb.AppendLine($"- **モデル名**: {gpu.Name}");
                sb.AppendLine($"- **製造元**: {gpu.AdapterManufacturer}");
                if (!string.IsNullOrEmpty(gpu.VideoProcessor))
                {
                    sb.AppendLine($"- **ビデオプロセッサ**: {gpu.VideoProcessor}");
                }
                sb.AppendLine($"- **ドライバーバージョン**: {gpu.DriverVersion}");
                sb.AppendLine();
            }
        }

        // BitLocker
        sb.AppendLine("### 🔐 BitLocker暗号化");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(hardware.BitLocker.Error))
        {
            sb.AppendLine($"⚠️ **エラー**: {hardware.BitLocker.Error}");
            if (!string.IsNullOrEmpty(hardware.BitLocker.Note))
            {
                sb.AppendLine($"- **注記**: {hardware.BitLocker.Note}");
            }
        }
        else if (hardware.BitLocker.Volumes.Count == 0)
        {
            sb.AppendLine("BitLockerで暗号化されたボリュームはありません");
        }
        else
        {
            foreach (var volume in hardware.BitLocker.Volumes)
            {
                sb.AppendLine($"#### ドライブ {volume.DriveLetter}");
                sb.AppendLine();
                sb.AppendLine($"- **暗号化状態**: {(volume.IsEncrypted ? "🔒 暗号化済み" : "🔓 暗号化なし")}");
                sb.AppendLine($"- **保護状態**: {volume.ProtectionStatus}");
                sb.AppendLine($"- **暗号化率**: {volume.EncryptionPercentage}%");

                if (volume.RecoveryKeys.Count > 0)
                {
                    sb.AppendLine($"- **回復キー**:");
                    foreach (var key in volume.RecoveryKeys)
                    {
                        sb.AppendLine($"  - `{key}`");
                    }
                }
                else if (!string.IsNullOrEmpty(volume.Error))
                {
                    sb.AppendLine($"- **回復キー**: ⚠️ {volume.Error}");
                }
                sb.AppendLine();
            }
        }

        // ストレージヘルス
        if (hardware.StorageHealth.Count > 0)
        {
            sb.AppendLine("### 💾 ストレージヘルス（SMART/NVMe）");
            sb.AppendLine();
            foreach (var storage in hardware.StorageHealth)
            {
                sb.AppendLine($"#### ドライブ #{storage.DriveNumber}");
                sb.AppendLine();
                sb.AppendLine($"- **モデル**: {storage.Model}");

                if (!string.IsNullOrEmpty(storage.Error))
                {
                    sb.AppendLine($"- **エラー**: ❌ {storage.Error}");
                    if (!string.IsNullOrEmpty(storage.Note))
                    {
                        sb.AppendLine($"- **注記**: {storage.Note}");
                    }
                }
                else
                {
                    if (!string.IsNullOrEmpty(storage.SerialNumber) && storage.SerialNumber != "不明")
                    {
                        sb.AppendLine($"- **シリアル番号**: {storage.SerialNumber}");
                    }
                    sb.AppendLine($"- **インターフェース**: {storage.InterfaceType}");
                    sb.AppendLine($"- **メディアタイプ**: {storage.MediaType}");
                    if (storage.CapacityGb > 0)
                    {
                        sb.AppendLine($"- **容量**: {storage.CapacityGb:F2} GB");
                    }

                    var healthIcon = storage.HealthStatus switch
                    {
                        "OK" => "✅",
                        "Warning" => "⚠️",
                        "Critical" => "❌",
                        _ => "❓"
                    };
                    sb.AppendLine($"- **健康状態**: {healthIcon} {storage.HealthStatus}");

                    if (storage.TemperatureCelsius.HasValue)
                    {
                        sb.AppendLine($"- **温度**: {storage.TemperatureCelsius.Value}°C");
                    }
                    if (storage.PowerOnHours.HasValue)
                    {
                        var days = storage.PowerOnHours.Value / 24;
                        sb.AppendLine($"- **通電時間**: {storage.PowerOnHours.Value:N0} 時間 ({days:N0} 日)");
                    }
                    if (storage.RemainingLifePercent.HasValue)
                    {
                        sb.AppendLine($"- **残り寿命（SSD）**: {storage.RemainingLifePercent.Value}%");
                    }
                    if (storage.TotalBytesWrittenGb.HasValue && storage.TotalBytesWrittenGb.Value > 0)
                    {
                        sb.AppendLine($"- **総書き込み量**: {storage.TotalBytesWrittenGb.Value:N2} GB");
                    }
                    if (storage.TotalBytesReadGb.HasValue && storage.TotalBytesReadGb.Value > 0)
                    {
                        sb.AppendLine($"- **総読み込み量**: {storage.TotalBytesReadGb.Value:N2} GB");
                    }
                    if (!string.IsNullOrEmpty(storage.CriticalWarning))
                    {
                        sb.AppendLine($"- **警告**: ⚠️ {storage.CriticalWarning}");
                    }

                    // SMART属性（重要なもののみ表示）
                    if (storage.SmartAttributes.Count > 0)
                    {
                        sb.AppendLine();
                        sb.AppendLine("**📊 SMART属性（重要項目）**");
                        sb.AppendLine();

                        // 重要なSMART属性のみ表示
                        var importantIds = new[] { 5, 9, 10, 12, 187, 197, 198, 199, 1000, 1001 };
                        var importantAttributes = storage.SmartAttributes
                            .Where(a => importantIds.Contains(a.Id))
                            .OrderBy(a => a.Id)
                            .ToList();

                        if (importantAttributes.Count > 0)
                        {
                            sb.AppendLine("| ID | 属性名 | 現在値 | 最悪値 | RAW値 |");
                            sb.AppendLine("|---|---|---|---|---|");

                            foreach (var attr in importantAttributes)
                            {
                                // 異常値の場合は警告アイコンを追加
                                var warningIcon = "";
                                if ((attr.Id == 5 || attr.Id == 197 || attr.Id == 198) && attr.RawValue > 0)
                                {
                                    warningIcon = " ⚠️";
                                }

                                sb.AppendLine($"| {attr.Id} | {attr.Name}{warningIcon} | {attr.CurrentValue} | {attr.WorstValue} | {attr.RawValue:N0} |");
                            }

                            sb.AppendLine();

                            // 残りの属性数を表示
                            var otherCount = storage.SmartAttributes.Count - importantAttributes.Count;
                            if (otherCount > 0)
                            {
                                sb.AppendLine($"> ℹ️ その他の属性 {otherCount} 個は JSON レポートに記録されています");
                            }
                        }
                    }
                }
                sb.AppendLine();
            }
        }

        // ウイルス対策情報
        sb.AppendLine("### 🛡️ ウイルス対策情報");
        sb.AppendLine();

        // Windows Defender情報
        sb.AppendLine("#### Windows Defender");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(hardware.Antivirus.WindowsDefender.Error))
        {
            sb.AppendLine($"⚠️ **エラー**: {hardware.Antivirus.WindowsDefender.Error}");
        }
        else
        {
            var enabledIcon = hardware.Antivirus.WindowsDefender.Enabled ? "✅" : "❌";
            sb.AppendLine($"- **状態**: {enabledIcon} {(hardware.Antivirus.WindowsDefender.Enabled ? "有効" : "無効")}");

            var rtProtectionIcon = hardware.Antivirus.WindowsDefender.RealtimeProtectionEnabled ? "✅" : "❌";
            sb.AppendLine($"- **リアルタイム保護**: {rtProtectionIcon} {(hardware.Antivirus.WindowsDefender.RealtimeProtectionEnabled ? "オン" : "オフ")}");

            if (!string.IsNullOrEmpty(hardware.Antivirus.WindowsDefender.SignatureLastUpdated))
            {
                var signatureIcon = hardware.Antivirus.WindowsDefender.SignatureUpToDate ? "✅" : "⚠️";
                var signatureStatus = hardware.Antivirus.WindowsDefender.SignatureUpToDate ? "最新" : "古い（7日以上前）";
                sb.AppendLine($"- **定義ファイル**: {signatureIcon} {hardware.Antivirus.WindowsDefender.SignatureLastUpdated} ({signatureStatus})");
            }

            if (!string.IsNullOrEmpty(hardware.Antivirus.WindowsDefender.LastScanDateTime))
            {
                sb.AppendLine($"- **最終スキャン**: {hardware.Antivirus.WindowsDefender.LastScanDateTime}");
            }

            sb.AppendLine($"- **最近の脅威検出数**: {hardware.Antivirus.WindowsDefender.RecentThreatsCount} 件");
        }
        sb.AppendLine();

        // USBスキャン結果
        if (hardware.Antivirus.UsbScan.Scanned)
        {
            sb.AppendLine("#### USBドライブスキャン結果");
            sb.AppendLine();
            sb.AppendLine($"- **スキャン対象**: `{hardware.Antivirus.UsbScan.ScanPath}`");

            var resultIcon = hardware.Antivirus.UsbScan.Result switch
            {
                "Clean" => "✅",
                "Threat" => "❌",
                "Error" => "⚠️",
                _ => "❓"
            };
            sb.AppendLine($"- **スキャン結果**: {resultIcon} **{hardware.Antivirus.UsbScan.Result}**");

            if (hardware.Antivirus.UsbScan.ThreatsFound > 0)
            {
                sb.AppendLine($"- **検出された脅威**: {hardware.Antivirus.UsbScan.ThreatsFound} 件");
                if (hardware.Antivirus.UsbScan.ThreatNames.Count > 0)
                {
                    sb.AppendLine("- **脅威の詳細**:");
                    foreach (var threat in hardware.Antivirus.UsbScan.ThreatNames)
                    {
                        sb.AppendLine($"  - ⚠️ {threat}");
                    }
                }
            }

            sb.AppendLine($"- **スキャン時間**: {hardware.Antivirus.UsbScan.ScanDurationSeconds:F1} 秒");

            if (!string.IsNullOrEmpty(hardware.Antivirus.UsbScan.Error))
            {
                sb.AppendLine($"- **エラー**: {hardware.Antivirus.UsbScan.Error}");
            }

            if (!string.IsNullOrEmpty(hardware.Antivirus.UsbScan.Warning))
            {
                sb.AppendLine();
                sb.AppendLine($"> ⚠️ **警告**: {hardware.Antivirus.UsbScan.Warning}");
            }
            sb.AppendLine();
        }
        else if (!string.IsNullOrEmpty(hardware.Antivirus.Error))
        {
            sb.AppendLine($"⚠️ **エラー**: {hardware.Antivirus.Error}");
            if (!string.IsNullOrEmpty(hardware.Antivirus.Note))
            {
                sb.AppendLine($"- **注記**: {hardware.Antivirus.Note}");
            }
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private string BuildStorageSection(StorageResult storage)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## 💾 ストレージ空き容量");
        sb.AppendLine();

        var statusIcon = storage.Status switch
        {
            "ok" => "✅",
            "warn" => "⚠️",
            "danger" => "❌",
            _ => "❓"
        };

        sb.AppendLine($"- **判定**: {statusIcon} {storage.Status.ToUpper()}");
        sb.AppendLine($"- **ドライブ**: {storage.Drive}");
        sb.AppendLine($"- **総容量**: {storage.TotalGb:F1} GB");
        sb.AppendLine($"- **使用済み**: {(storage.TotalGb - storage.FreeGb):F1} GB");
        sb.AppendLine($"- **空き容量**: {storage.FreeGb:F1} GB ({storage.FreePercent:F1}%)");

        if (!string.IsNullOrEmpty(storage.Recommendation))
        {
            sb.AppendLine($"- **推奨**: {storage.Recommendation}");
        }

        if (!string.IsNullOrEmpty(storage.Error))
        {
            sb.AppendLine($"- **エラー**: {storage.Error}");
        }

        sb.AppendLine();

        return sb.ToString();
    }

    private string BuildKeyboardSection(KeyboardResult keyboard)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## ⌨️ キーボード検査");
        sb.AppendLine();

        var resultIcon = keyboard.Result switch
        {
            "pass" => "✅",
            "warn" => "⚠️",
            "fail" => "❌",
            _ => "❓"
        };

        sb.AppendLine($"- **判定**: {resultIcon} {keyboard.Result.ToUpper()}");
        sb.AppendLine($"- **レイアウト**: {keyboard.Layout}");
        sb.AppendLine($"- **押下キー数**: {keyboard.PressedKeys}/{keyboard.TotalKeys}");

        if (keyboard.MissingKeys.Count > 0)
        {
            sb.AppendLine($"- **未押下キー**: {string.Join(", ", keyboard.MissingKeys)}");
        }

        if (!string.IsNullOrEmpty(keyboard.Note))
        {
            sb.AppendLine($"- **注記**: {keyboard.Note}");
        }

        if (!string.IsNullOrEmpty(keyboard.Error))
        {
            sb.AppendLine($"- **エラー**: {keyboard.Error}");
        }

        sb.AppendLine();
        return sb.ToString();
    }

    private string BuildMicrophoneSection(MicrophoneResult mic)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## 🎤 マイク検査");
        sb.AppendLine();

        sb.AppendLine($"- **録音**: {(mic.Recorded ? "✅ 成功" : "❌ 失敗")}");
        sb.AppendLine($"- **ユーザー確認**: {(mic.UserConfirmed ? "✅ 正常" : "❌ 異常")}");
        sb.AppendLine($"- **デバイス名**: {mic.DeviceName}");

        if (!string.IsNullOrEmpty(mic.File))
        {
            sb.AppendLine($"- **録音ファイル**: `{mic.File}`");
        }

        if (!string.IsNullOrEmpty(mic.Error))
        {
            sb.AppendLine($"- **エラー**: {mic.Error}");
        }

        if (!string.IsNullOrEmpty(mic.Note))
        {
            sb.AppendLine($"- **注記**: {mic.Note}");
        }

        sb.AppendLine();
        return sb.ToString();
    }

    private string BuildSpeakerSection(SpeakerResult speaker)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## 🔊 スピーカー検査");
        sb.AppendLine();

        sb.AppendLine($"- **左チャンネル**: {(speaker.Left ? "✅ 正常" : "❌ 異常")}");
        sb.AppendLine($"- **右チャンネル**: {(speaker.Right ? "✅ 正常" : "❌ 異常")}");
        sb.AppendLine($"- **デバイス名**: {speaker.DeviceName}");

        if (!string.IsNullOrEmpty(speaker.Note))
        {
            sb.AppendLine($"- **注記**: {speaker.Note}");
        }

        sb.AppendLine();
        return sb.ToString();
    }

    private string BuildCameraSection(CameraResult camera)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## 📷 カメラ検査");
        sb.AppendLine();

        sb.AppendLine($"- **撮影**: {(camera.Captured ? "✅ 成功" : "❌ 失敗")}");
        sb.AppendLine($"- **デバイス名**: {camera.DeviceName}");

        if (!string.IsNullOrEmpty(camera.File))
        {
            sb.AppendLine($"- **画像ファイル**: `{camera.File}`");
        }

        if (!string.IsNullOrEmpty(camera.Error))
        {
            sb.AppendLine($"- **エラー**: {camera.Error}");
        }

        if (!string.IsNullOrEmpty(camera.Note))
        {
            sb.AppendLine($"- **注記**: {camera.Note}");
        }

        sb.AppendLine();
        return sb.ToString();
    }

    private string BuildTrackpadSection(TrackpadResult trackpad)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## 🖱️ トラックパッド検査");
        sb.AppendLine();

        var resultIcon = trackpad.Result switch
        {
            "pass" => "✅",
            "warn" => "⚠️",
            "fail" => "❌",
            _ => "❓"
        };

        sb.AppendLine($"- **判定**: {resultIcon} {trackpad.Result.ToUpper()}");
        sb.AppendLine($"- **カーソル移動**: {(trackpad.CursorMoved ? "✅ 正常" : "❌ 異常")}");
        sb.AppendLine($"- **左クリック**: {(trackpad.LeftClick ? "✅ 正常" : "❌ 異常")}");
        sb.AppendLine($"- **右クリック**: {(trackpad.RightClick ? "✅ 正常" : "❌ 異常")}");
        sb.AppendLine($"- **スクロール**: {(trackpad.ScrollDetected ? "✅ 正常" : "❌ 異常")}");

        if (!string.IsNullOrEmpty(trackpad.Note))
        {
            sb.AppendLine($"- **注記**: {trackpad.Note}");
        }

        if (!string.IsNullOrEmpty(trackpad.Error))
        {
            sb.AppendLine($"- **エラー**: {trackpad.Error}");
        }

        sb.AppendLine();
        return sb.ToString();
    }

    private string BuildCpuSection(CpuResult cpu)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## 🖥️ CPU簡易負荷テスト");
        sb.AppendLine();

        var testIcon = cpu.StressTest switch
        {
            "completed" => "✅",
            "failed" => "❌",
            "not_started" => "❓",
            _ => "❓"
        };

        sb.AppendLine($"- **ストレステスト**: {testIcon} {cpu.StressTest}");
        sb.AppendLine($"- **テスト時間**: {cpu.DurationSec} 秒");
        sb.AppendLine($"- **異常検出**: {(cpu.Abnormal ? "❌ あり" : "✅ なし")}");

        if (cpu.Temperature.HasValue)
        {
            sb.AppendLine($"- **温度**: {cpu.Temperature.Value:F1}°C");
        }

        if (!string.IsNullOrEmpty(cpu.Error))
        {
            sb.AppendLine($"- **エラー**: {cpu.Error}");
        }

        if (!string.IsNullOrEmpty(cpu.Note))
        {
            sb.AppendLine($"- **注記**: {cpu.Note}");
        }

        sb.AppendLine();
        return sb.ToString();
    }
}
