using System.IO;
using System.Text;
using RukiCheck.Models;

namespace RukiCheck.Infrastructure;

/// <summary>
/// Markdown レポート生成サービス
/// </summary>
public class MarkdownReportGenerator
{
    /// <summary>
    /// Markdownレポートを生成
    /// </summary>
    public void Generate(InspectionReport report, string outputPath)
    {
        var markdown = BuildMarkdown(report);
        File.WriteAllText(outputPath, markdown, new UTF8Encoding(true)); // UTF-8 BOM
    }

    private string BuildMarkdown(InspectionReport report)
    {
        var sb = new StringBuilder();

        // タイトル
        sb.AppendLine("# 🔍 RukiCheck 検品レポート");
        sb.AppendLine();

        // メタ情報
        sb.AppendLine("## 📋 検品情報");
        sb.AppendLine();
        sb.AppendLine($"- **管理番号**: {report.Meta.ManagementId}");
        sb.AppendLine($"- **検品日**: {report.Meta.InspectionDate}");
        sb.AppendLine($"- **検品者**: {report.Meta.Inspector}");
        sb.AppendLine($"- **レポート作成日時**: {report.Meta.CreatedAt}");
        sb.AppendLine();

        // ハードウェア情報
        if (report.Hardware != null)
        {
            sb.AppendLine(BuildHardwareSection(report.Hardware));
        }

        // ストレージ
        if (report.Storage != null)
        {
            sb.AppendLine(BuildStorageSection(report.Storage));
        }

        // キーボード
        if (report.Keyboard != null)
        {
            sb.AppendLine(BuildKeyboardSection(report.Keyboard));
        }

        // マイク
        if (report.Microphone != null)
        {
            sb.AppendLine(BuildMicrophoneSection(report.Microphone));
        }

        // スピーカー
        if (report.Speaker != null)
        {
            sb.AppendLine(BuildSpeakerSection(report.Speaker));
        }

        // カメラ
        if (report.Camera != null)
        {
            sb.AppendLine(BuildCameraSection(report.Camera));
        }

        // トラックパッド
        if (report.Trackpad != null)
        {
            sb.AppendLine(BuildTrackpadSection(report.Trackpad));
        }

        // CPU
        if (report.Cpu != null)
        {
            sb.AppendLine(BuildCpuSection(report.Cpu));
        }

        // フッター
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("*Generated by RukiCheck Portable Inspection Tool*");
        sb.AppendLine();

        return sb.ToString();
    }

    private string BuildHardwareSection(HardwareInfoResult hardware)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## 🖥️ ハードウェア情報");
        sb.AppendLine();

        // システム情報
        sb.AppendLine("### 🏷️ システム情報");
        sb.AppendLine();
        sb.AppendLine($"- **メーカー**: {hardware.System.Manufacturer}");
        sb.AppendLine($"- **型番**: {hardware.System.Model}");
        sb.AppendLine($"- **シリアルナンバー**: {hardware.System.SerialNumber}");
        sb.AppendLine($"- **BIOSバージョン**: {hardware.System.BiosVersion}");
        sb.AppendLine();

        // CPU
        sb.AppendLine("### 💻 CPU");
        sb.AppendLine();
        sb.AppendLine($"- **モデル名**: {hardware.Cpu.Name}");
        sb.AppendLine($"- **製造元**: {hardware.Cpu.Manufacturer}");
        sb.AppendLine($"- **物理コア数**: {hardware.Cpu.Cores} コア");
        sb.AppendLine($"- **論理プロセッサ数**: {hardware.Cpu.LogicalProcessors} スレッド");
        sb.AppendLine($"- **最大クロック速度**: {hardware.Cpu.MaxClockMhz / 1000.0:F2} GHz");
        sb.AppendLine($"- **アーキテクチャ**: {hardware.Cpu.Architecture}");
        sb.AppendLine();

        // メモリ
        sb.AppendLine("### 🧠 メモリ");
        sb.AppendLine();
        sb.AppendLine($"- **総容量**: {hardware.Memory.TotalGb:F2} GB");
        sb.AppendLine($"- **メモリ種別**: {hardware.Memory.Type}");
        sb.AppendLine($"- **速度**: {hardware.Memory.SpeedMhz} MHz");
        sb.AppendLine($"- **スロット数**: {hardware.Memory.Slots}");
        sb.AppendLine();

        if (hardware.Memory.Modules.Count > 0)
        {
            sb.AppendLine("#### メモリモジュール詳細");
            sb.AppendLine();
            sb.AppendLine("| スロット | 容量 | メーカー | 速度 | パーツ番号 |");
            sb.AppendLine("|---------|------|---------|------|-----------|");
            for (int i = 0; i < hardware.Memory.Modules.Count; i++)
            {
                var module = hardware.Memory.Modules[i];
                sb.AppendLine($"| #{i + 1} | {module.CapacityGb:F2} GB | {module.Manufacturer} | {module.SpeedMhz} MHz | {module.PartNumber} |");
            }
            sb.AppendLine();
        }

        // GPU
        if (hardware.Gpus.Count > 0)
        {
            sb.AppendLine("### 🎮 GPU（グラフィックカード）");
            sb.AppendLine();
            foreach (var gpu in hardware.Gpus)
            {
                sb.AppendLine($"- **モデル名**: {gpu.Name}");
                sb.AppendLine($"- **製造元**: {gpu.AdapterManufacturer}");
                if (!string.IsNullOrEmpty(gpu.VideoProcessor))
                {
                    sb.AppendLine($"- **ビデオプロセッサ**: {gpu.VideoProcessor}");
                }
                sb.AppendLine($"- **ドライバーバージョン**: {gpu.DriverVersion}");
                sb.AppendLine();
            }
        }

        // BitLocker
        sb.AppendLine("### 🔐 BitLocker暗号化");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(hardware.BitLocker.Error))
        {
            sb.AppendLine($"⚠️ **エラー**: {hardware.BitLocker.Error}");
            if (!string.IsNullOrEmpty(hardware.BitLocker.Note))
            {
                sb.AppendLine($"- **注記**: {hardware.BitLocker.Note}");
            }
        }
        else if (hardware.BitLocker.Volumes.Count == 0)
        {
            sb.AppendLine("BitLockerで暗号化されたボリュームはありません");
        }
        else
        {
            foreach (var volume in hardware.BitLocker.Volumes)
            {
                sb.AppendLine($"#### ドライブ {volume.DriveLetter}");
                sb.AppendLine();
                sb.AppendLine($"- **暗号化状態**: {(volume.IsEncrypted ? "🔒 暗号化済み" : "🔓 暗号化なし")}");
                sb.AppendLine($"- **保護状態**: {volume.ProtectionStatus}");
                sb.AppendLine($"- **暗号化率**: {volume.EncryptionPercentage}%");

                if (volume.RecoveryKeys.Count > 0)
                {
                    sb.AppendLine($"- **回復キー**:");
                    foreach (var key in volume.RecoveryKeys)
                    {
                        sb.AppendLine($"  - `{key}`");
                    }
                }
                else if (!string.IsNullOrEmpty(volume.Error))
                {
                    sb.AppendLine($"- **回復キー**: ⚠️ {volume.Error}");
                }
                sb.AppendLine();
            }
        }

        // ストレージヘルス
        if (hardware.StorageHealth.Count > 0)
        {
            sb.AppendLine("### 💾 ストレージヘルス（SMART/NVMe）");
            sb.AppendLine();
            foreach (var storage in hardware.StorageHealth)
            {
                sb.AppendLine($"#### ドライブ #{storage.DriveNumber}");
                sb.AppendLine();
                sb.AppendLine($"- **モデル**: {storage.Model}");

                if (!string.IsNullOrEmpty(storage.Error))
                {
                    sb.AppendLine($"- **エラー**: ❌ {storage.Error}");
                    if (!string.IsNullOrEmpty(storage.Note))
                    {
                        sb.AppendLine($"- **注記**: {storage.Note}");
                    }
                }
                else
                {
                    if (!string.IsNullOrEmpty(storage.SerialNumber) && storage.SerialNumber != "不明")
                    {
                        sb.AppendLine($"- **シリアル番号**: {storage.SerialNumber}");
                    }
                    sb.AppendLine($"- **インターフェース**: {storage.InterfaceType}");
                    sb.AppendLine($"- **メディアタイプ**: {storage.MediaType}");
                    if (storage.CapacityGb > 0)
                    {
                        sb.AppendLine($"- **容量**: {storage.CapacityGb:F2} GB");
                    }

                    var healthIcon = storage.HealthStatus switch
                    {
                        "OK" => "✅",
                        "Warning" => "⚠️",
                        "Critical" => "❌",
                        _ => "❓"
                    };
                    sb.AppendLine($"- **健康状態**: {healthIcon} {storage.HealthStatus}");

                    if (storage.TemperatureCelsius.HasValue)
                    {
                        sb.AppendLine($"- **温度**: {storage.TemperatureCelsius.Value}°C");
                    }
                    if (storage.PowerOnHours.HasValue)
                    {
                        var days = storage.PowerOnHours.Value / 24;
                        sb.AppendLine($"- **通電時間**: {storage.PowerOnHours.Value:N0} 時間 ({days:N0} 日)");
                    }
                    if (storage.RemainingLifePercent.HasValue)
                    {
                        sb.AppendLine($"- **残り寿命（SSD）**: {storage.RemainingLifePercent.Value}%");
                    }
                    if (storage.TotalBytesWrittenGb.HasValue && storage.TotalBytesWrittenGb.Value > 0)
                    {
                        sb.AppendLine($"- **総書き込み量**: {storage.TotalBytesWrittenGb.Value:N2} GB");
                    }
                    if (storage.TotalBytesReadGb.HasValue && storage.TotalBytesReadGb.Value > 0)
                    {
                        sb.AppendLine($"- **総読み込み量**: {storage.TotalBytesReadGb.Value:N2} GB");
                    }
                    if (!string.IsNullOrEmpty(storage.CriticalWarning))
                    {
                        sb.AppendLine($"- **警告**: ⚠️ {storage.CriticalWarning}");
                    }
                }
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    private string BuildStorageSection(StorageResult storage)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## 💾 ストレージ空き容量");
        sb.AppendLine();

        var statusIcon = storage.Status switch
        {
            "ok" => "✅",
            "warn" => "⚠️",
            "danger" => "❌",
            _ => "❓"
        };

        sb.AppendLine($"- **判定**: {statusIcon} {storage.Status.ToUpper()}");
        sb.AppendLine($"- **ドライブ**: {storage.DriveName}");
        sb.AppendLine($"- **総容量**: {storage.TotalGb:F1} GB");
        sb.AppendLine($"- **使用済み**: {storage.UsedGb:F1} GB");
        sb.AppendLine($"- **空き容量**: {storage.FreeGb:F1} GB ({storage.FreePercent:F1}%)");
        sb.AppendLine();

        return sb.ToString();
    }

    private string BuildKeyboardSection(KeyboardResult keyboard)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## ⌨️ キーボード検査");
        sb.AppendLine();

        sb.AppendLine($"- **確認済みキー数**: {keyboard.ConfirmedKeys}/{keyboard.TotalKeys}");
        sb.AppendLine($"- **完了**: {(keyboard.Completed ? "✅ はい" : "❌ いいえ")}");

        if (keyboard.MissingKeys.Count > 0)
        {
            sb.AppendLine($"- **未確認キー**: {string.Join(", ", keyboard.MissingKeys)}");
        }

        if (!string.IsNullOrEmpty(keyboard.Note))
        {
            sb.AppendLine($"- **注記**: {keyboard.Note}");
        }

        sb.AppendLine();
        return sb.ToString();
    }

    private string BuildMicrophoneSection(MicrophoneResult mic)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## 🎤 マイク検査");
        sb.AppendLine();

        sb.AppendLine($"- **録音**: {(mic.Recorded ? "✅ 成功" : "❌ 失敗")}");
        sb.AppendLine($"- **ユーザー確認**: {(mic.UserConfirmed ? "✅ 正常" : "❌ 異常")}");
        sb.AppendLine($"- **デバイス名**: {mic.DeviceName}");

        if (!string.IsNullOrEmpty(mic.File))
        {
            sb.AppendLine($"- **録音ファイル**: `{mic.File}`");
        }

        if (!string.IsNullOrEmpty(mic.Error))
        {
            sb.AppendLine($"- **エラー**: {mic.Error}");
        }

        if (!string.IsNullOrEmpty(mic.Note))
        {
            sb.AppendLine($"- **注記**: {mic.Note}");
        }

        sb.AppendLine();
        return sb.ToString();
    }

    private string BuildSpeakerSection(SpeakerResult speaker)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## 🔊 スピーカー検査");
        sb.AppendLine();

        sb.AppendLine($"- **左チャンネル**: {(speaker.Left ? "✅ 正常" : "❌ 異常")}");
        sb.AppendLine($"- **右チャンネル**: {(speaker.Right ? "✅ 正常" : "❌ 異常")}");
        sb.AppendLine($"- **デバイス名**: {speaker.DeviceName}");

        if (!string.IsNullOrEmpty(speaker.Note))
        {
            sb.AppendLine($"- **注記**: {speaker.Note}");
        }

        sb.AppendLine();
        return sb.ToString();
    }

    private string BuildCameraSection(CameraResult camera)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## 📷 カメラ検査");
        sb.AppendLine();

        sb.AppendLine($"- **撮影**: {(camera.Captured ? "✅ 成功" : "❌ 失敗")}");
        sb.AppendLine($"- **デバイス名**: {camera.DeviceName}");

        if (!string.IsNullOrEmpty(camera.File))
        {
            sb.AppendLine($"- **画像ファイル**: `{camera.File}`");
        }

        if (!string.IsNullOrEmpty(camera.Error))
        {
            sb.AppendLine($"- **エラー**: {camera.Error}");
        }

        if (!string.IsNullOrEmpty(camera.Note))
        {
            sb.AppendLine($"- **注記**: {camera.Note}");
        }

        sb.AppendLine();
        return sb.ToString();
    }

    private string BuildTrackpadSection(TrackpadResult trackpad)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## 🖱️ トラックパッド検査");
        sb.AppendLine();

        sb.AppendLine($"- **カーソル移動**: {(trackpad.CursorMovement ? "✅ 正常" : "❌ 異常")}");
        sb.AppendLine($"- **左クリック**: {(trackpad.LeftClick ? "✅ 正常" : "❌ 異常")}");
        sb.AppendLine($"- **右クリック**: {(trackpad.RightClick ? "✅ 正常" : "❌ 異常")}");
        sb.AppendLine($"- **スクロール**: {(trackpad.Scroll ? "✅ 正常" : "❌ 異常")}");

        if (!string.IsNullOrEmpty(trackpad.Note))
        {
            sb.AppendLine($"- **注記**: {trackpad.Note}");
        }

        sb.AppendLine();
        return sb.ToString();
    }

    private string BuildCpuSection(CpuResult cpu)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## 🖥️ CPU簡易負荷テスト");
        sb.AppendLine();

        var passIcon = cpu.Passed ? "✅" : "❌";
        sb.AppendLine($"- **判定**: {passIcon} {(cpu.Passed ? "正常" : "異常")}");
        sb.AppendLine($"- **テスト時間**: {cpu.TestDurationSeconds} 秒");
        sb.AppendLine($"- **フリーズ**: {(cpu.Freeze ? "❌ あり" : "✅ なし")}");
        sb.AppendLine($"- **異常停止**: {(cpu.Crash ? "❌ あり" : "✅ なし")}");

        if (!string.IsNullOrEmpty(cpu.Error))
        {
            sb.AppendLine($"- **エラー**: {cpu.Error}");
        }

        if (!string.IsNullOrEmpty(cpu.Note))
        {
            sb.AppendLine($"- **注記**: {cpu.Note}");
        }

        sb.AppendLine();
        return sb.ToString();
    }
}
